Add defaults overcloud_image as overcloud-full
In patch [1] we removed the hard-code overcloud-full image name,
but the default var is only set in tqe[2] not tq. This leads to
oooq deployment failing on convert-image task with
error: 'overcloud_image' is undefined

Adding in `overcloud_image` var in tq common role defaults to
resolves the Bug mentioned in Closes-Bug.

[1] https://review.opendev.org/c/openstack/tripleo-quickstart/+/801703
[2] https://opendev.org/openstack/tripleo-quickstart-extras/src/branch/master/roles/extras-common/defaults/main.yml#L170

Closes-Bug: #1943820
Change-Id: I075e168a9cc10b76841ef93af0e54c6abf48dd76