Avoid problematic recreation of virtualenv
Recreation of a virtualenv can cause errors like below when there are
leftover python processes running (can really happen).

IOError: [Errno 26] Text file busy

Also disables few annoying pip warnings.

Change-Id: I1c55e72acff024195f3ee6388dd2dfcbd1e5f466
Closes-Bug: #1826129
Related-Bug: #1792375